# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartaoCredito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Descrição')),
                ('numero', models.CharField(max_length=80, verbose_name='Número do Cartão de Crédito')),
                ('observacao', models.TextField(blank=True, default=' ', verbose_name='Observação')),
                ('dia_fechamento_fatura', models.IntegerField(blank=True, null=True, verbose_name='Dia de fechamento da fatura')),
                ('dia_vencimento_fatura', models.IntegerField(blank=True, null=True, verbose_name='Dia de pagamento da fatura')),
            ],
            options={
                'verbose_name': 'Cartão de Crédito',
                'verbose_name_plural': 'Cartões de Crédito',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Classificação',
                'verbose_name_plural': 'Classificações',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome')),
                ('ehContaBancaria', models.BooleanField(verbose_name='É uma conta bancária')),
            ],
        ),
        migrations.CreateModel(
            name='LancamentoFinanceiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='Descrição')),
                ('data', models.DateField(verbose_name='Data')),
                ('valor', models.DecimalField(decimal_places=10, default=0, max_digits=19, verbose_name='Valor')),
                ('status', models.CharField(blank=True, choices=[(0, 'Não Pago'), (1, 'Pago')], default='0 ', max_length=1, null=True)),
                ('tipo', models.CharField(choices=[(1, 'A Receber'), (2, 'A Pagar')], max_length=1)),
                ('cartaoCredito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financas.CartaoCredito')),
                ('classificacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financas.Classificacao')),
                ('conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financas.Conta')),
            ],
            options={
                'verbose_name': 'Lançamento Financeiro',
                'verbose_name_plural': 'Lançamentos Financeiros',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Saque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(default=' ', max_length=50, verbose_name='Descrição')),
                ('data_saque', models.DateTimeField(verbose_name='Data do saque')),
                ('valor_saque', models.DecimalField(decimal_places=10, default=0, max_digits=19, verbose_name='Valor saque')),
                ('conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financas.Conta')),
            ],
        ),
    ]
