# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Informações adicionais'),
        ),
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='status',
            field=models.CharField(blank=True, choices=[(0, 'Não Pago'), (1, 'Pago')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='tipo',
            field=models.CharField(blank=True, choices=[(1, 'A Receber'), (2, 'A Pagar')], max_length=1),
        ),
    ]
