# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0003_auto_20170901_0253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartaocredito',
            options={'ordering': ['nome'], 'verbose_name': 'Cartão de Crédito', 'verbose_name_plural': 'Cartões de Crédito'},
        ),
        migrations.RemoveField(
            model_name='cartaocredito',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='cartaocredito',
            name='observacao',
        ),
        migrations.AddField(
            model_name='cartaocredito',
            name='bandeira',
            field=models.IntegerField(blank=True, choices=[(1, 'Visa'), (2, 'Mastercard'), (99, 'Outra')], default='1', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='cartaocredito',
            name='conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financas.Conta'),
        ),
        migrations.AddField(
            model_name='cartaocredito',
            name='valor_limite',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19, verbose_name='Limite'),
        ),
        migrations.AlterField(
            model_name='cartaocredito',
            name='dia_vencimento_fatura',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dia de vencimento da fatura'),
        ),
    ]
