# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 02:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0003_cartaocredito'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartaocredito',
            old_name='descricao',
            new_name='nome',
        ),
    ]
