# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0004_auto_20170721_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaocredito',
            name='observacao',
            field=models.TextField(blank=True, default=' ', verbose_name='Observação'),
        ),
    ]
