# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0007_auto_20170726_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='valor',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19, verbose_name='Valor'),
        ),
    ]
