# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0009_auto_20170726_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartaocredito',
            name='data_fechamento_fatura',
        ),
        migrations.AddField(
            model_name='cartaocredito',
            name='dia_fechamento_fatura',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dia de fechamento da fatura'),
        ),
    ]
