# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0010_auto_20170726_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'Não Pago'), ('1', 'Pago')], default='0 ', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cartaocredito',
            name='dia_fechamento_fatura',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dia de fechamento da fatura'),
        ),
    ]
